sudo: false
language: python
services:
  - docker
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - env: TOX_ENV=py37
      python: 3.7

install:
  - pip install tox
  - pip install codecov
  - pip install pytest-cov


script: travis_retry tox -e $TOX_ENV

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)


