version: '3'
services:
    elasticsearch:
        image: elasticsearch:7.12.1
        container_name: elasticsearch
        environment:
            ES_JAVA_OPTS: "-Xmx512m -Xms512m"
            discovery.type: single-node
        env_file: .env
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            -   type: volume
                source: elasticsearch
                target: /usr/share/elasticsearch/data
        networks:
            - elc

    gazprom_test_task_jokes:
        restart: always
        build:
            context: .
        container_name: gazprom_test_task_jokes
        ports:
            - 8888:8888
        env_file: .env
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        networks:
            - elc

volumes:
    elasticsearch:
        driver: local

networks:
    elc:
        driver: bridge
